apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.19.6
    instancetype.kubevirt.io/default-instancetype: u1.medium
    instancetype.kubevirt.io/default-preference: centos.stream9
    kubevirt.io/created-by: 9be76ed9-9f81-46eb-b45b-13577f25886f
  name: centos-stream9-salmon-clownfish-82
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: '32212254720'
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  volumeMode: Block
  volumeName: pvc-1d9def3e-f389-49a5-b383-81ab30e11634
